# Generated by Django 5.0.14 on 2026-08-18 02:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nombre Espacio')),
                ('code', models.CharField(db_index=True, help_text='Ej: CANCHA-01, SALON-EVENTOS, PISCINA-01', max_length=30, unique=True, verbose_name='Código Interno')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación Referencia')),
                ('capacity', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='Capacidad Máxima Personas')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa por Hora (COP)')),
                ('requires_employee_approval', models.BooleanField(default=False, help_text='Si es True, cliente reserva como pendiente y empleado aprueba', verbose_name='Requiere Aprobación Empleado')),
                ('min_reservation_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='Mínimo Minutos Reserva')),
                ('max_reservation_minutes', models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(720)], verbose_name='Máximo Minutos Reserva')),
                ('advance_days_limit', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Días Máximo Anticipación')),
                ('cancellation_penalty_hours', models.PositiveIntegerField(default=6, help_text='Antelación mínima para cancelar sin penalización', verbose_name='Horas Penalidad Cancelación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo / Disponible'), ('MAINTENANCE', 'En Mantenimiento'), ('INACTIVE', 'Inactivo')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spaces/%Y/%m/', verbose_name='Foto Espacio')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'ordering': ['space_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Nombre Tipo')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, default='🏟️', max_length=30, null=True, verbose_name='Icono (emoji/clase CSS)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Espacio',
                'verbose_name_plural': 'Tipos de Espacios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día Semana (0=Lun, 6=Dom)')),
                ('open_time', models.TimeField(verbose_name='Hora Apertura')),
                ('close_time', models.TimeField(verbose_name='Hora Cierre')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado este día')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='reservations.space', verbose_name='Espacio')),
            ],
            options={
                'verbose_name': 'Horario Operación',
                'verbose_name_plural': 'Horarios Operación',
                'ordering': ['space', 'weekday'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Festivo / Evento')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('spaces_closed', models.ManyToManyField(blank=True, related_name='holidays', to='reservations.space', verbose_name='Espacios cerrados (vacíos = todos)')),
            ],
            options={
                'verbose_name': 'Festivo / Cierre Especial',
                'verbose_name_plural': 'Festivos / Cierres Especiales',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='space',
            name='space_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='reservations.spacetype', verbose_name='Tipo Espacio'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Fecha/Hora Inicio')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='Fecha/Hora Fin')),
                ('total_minutes', models.PositiveIntegerField(editable=False, verbose_name='Total Minutos')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total a Pagar (COP)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente Aprobación'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada'), ('REJECTED', 'Rechazada'), ('NO_SHOW', 'No Asistió')], db_index=True, default='CONFIRMED', max_length=20, verbose_name='Estado Reserva')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PAID', 'Pagado (Presencial)'), ('EXEMPT', 'Exento')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado Pago')),
                ('payment_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('guests_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número Invitados')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notas Adicionales')),
                ('cancellation_reason', models.TextField(blank=True, max_length=300, null=True, verbose_name='Motivo Cancelación / Rechazo')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cancelación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cumplimiento')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='Puntos Fidelización Otorgados')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Cliente que reserva o Empleado/Admin que agenda', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('payment_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Pago Recibido por')),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.space', verbose_name='Espacio Reservado')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['space', 'start_time', 'end_time'], name='reservation_space_i_a1b24c_idx'), models.Index(fields=['user', 'status'], name='reservation_user_id_b23f11_idx'), models.Index(fields=['status', 'start_time'], name='reservation_status_684b4f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='chk_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('guests_count__gte', 1)), name='chk_guests_min_1'),
        ),
        migrations.AlterUniqueTogether(
            name='operatinghours',
            unique_together={('space', 'weekday')},
        ),
        migrations.AlterUniqueTogether(
            name='space',
            unique_together={('space_type', 'name')},
        ),
    ]
