# Generated by Django 5.0.14 on 2026-08-18 02:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Nombre Producto')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Código SKU')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('unit_measure', models.CharField(choices=[('UNIT', 'Unidad'), ('LITER', 'Litro'), ('KILO', 'Kilo'), ('ML', 'Mililitro')], default='UNIT', max_length=10, verbose_name='Unidad Medida')),
                ('unit_content', models.DecimalField(decimal_places=2, default=1, help_text='Ej: 330 para gaseosa 330ml', max_digits=10, verbose_name='Contenido por unidad')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta (COP)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario (COP)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Actual')),
                ('min_stock', models.PositiveIntegerField(default=5, help_text='Alerta cuando baja de este valor', verbose_name='Stock Mínimo')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='Disponible para pedidos')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='Foto Producto')),
                ('allergens', models.TextField(blank=True, max_length=300, null=True, verbose_name='Alérgenos / Advertencias')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías (kcal)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Nombre Categoría')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, default='🥤', max_length=20, null=True, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden visual')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría Producto',
                'verbose_name_plural': 'Categorías Productos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True, verbose_name='Número Pedido')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente (Sin pagar)'), ('PREPARING', 'Preparando'), ('READY', 'Listo para Entregar'), ('DELIVERED', 'Entregado'), ('PAID', 'Pagado y Completado'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado Pedido')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta (Presencial)'), ('TRANSFER', 'Transferencia Bancaria'), ('MEMBERSHIP', 'Descuento Membresía')], max_length=30, null=True, verbose_name='Método Pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Impuesto')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Impuesto')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Descuento')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Descuento')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Total a Pagar')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto Pagado')),
                ('points_used', models.PositiveIntegerField(default=0, verbose_name='Puntos Fidelización Utilizados')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notas Pedido')),
                ('pickup_window_start', models.DateTimeField(blank=True, null=True, verbose_name='Horario Recogida Inicio')),
                ('pickup_window_end', models.DateTimeField(blank=True, null=True, verbose_name='Horario Recogida Fin')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Entregado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cancelación')),
                ('cancellation_reason', models.TextField(blank=True, max_length=300, null=True, verbose_name='Motivo Cancelación')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='Puntos Fidelización Otorgados')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_cancelled', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_paid', to=settings.AUTH_USER_MODEL, verbose_name='Pago Registrado por')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refreshment_orders', to='reservations.reservation', verbose_name='Reserva asociada (opcional)')),
                ('taken_by', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role__in': ['ADMIN', 'EMPLOYEE']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_taken', to=settings.AUTH_USER_MODEL, verbose_name='Tomado por (Empleado/Admin)')),
            ],
            options={
                'verbose_name': 'Pedido Refresquería',
                'verbose_name_plural': 'Pedidos Refresquería',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad')),
                ('unit_price_at_purchase', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Precio Unitario en el momento')),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Total Línea')),
                ('notes', models.CharField(blank=True, help_text='Ej: Sin azúcar, sin hielo, etc.', max_length=200, null=True, verbose_name='Nota item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='refreshments.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='refreshments.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item Pedido',
                'verbose_name_plural': 'Items Pedido',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='refreshments.productcategory', verbose_name='Categoría'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='refreshment_client__c96668_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='refreshment_status_76fc16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
    ]
