# Generated by Django 5.0.14 on 2026-08-18 02:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refreshments', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre Nivel')),
                ('min_points', models.PositiveIntegerField(unique=True, verbose_name='Puntos Mínimos')),
                ('color', models.CharField(default='#808080', max_length=10, verbose_name='Color (hex)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='% Descuento Base')),
                ('benefits', models.TextField(blank=True, max_length=500, null=True, verbose_name='Beneficios')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Nivel Fidelización',
                'verbose_name_plural': 'Niveles Fidelización',
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='RewardCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Premio')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('points_required', models.PositiveIntegerField(db_index=True, verbose_name='Puntos Requeridos')),
                ('category', models.CharField(blank=True, default='General', max_length=80, null=True, verbose_name='Categoría')),
                ('stock', models.PositiveIntegerField(default=0, help_text='0 = stock ilimitado (premio virtual)', verbose_name='Unidades Disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/%Y/%m/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premio Catálogo',
                'verbose_name_plural': 'Premios Catálogo',
                'ordering': ['points_required', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('RESERVATION', 'Reserva Completada'), ('REFRESHMENT', 'Pedido Refresquería Pagado'), ('REFERRAL', 'Referido Nuevo Miembro'), ('BIRTHDAY', 'Regalo Cumpleaños'), ('MEMBERSHIP', 'Renovación Membresía')], db_index=True, max_length=30, unique=True, verbose_name='Tipo de Acción')),
                ('points_amount', models.PositiveIntegerField(default=10, verbose_name='Puntos Base')),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=0, help_text='Opcional: puntos adicionales por monto gastado', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Puntos por cada $1000 COP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción Regla')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de Fidelización',
                'verbose_name_plural': 'Reglas de Fidelización',
                'ordering': ['action_type'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_points', models.IntegerField(default=0, verbose_name='Puntos Actuales')),
                ('lifetime_points', models.IntegerField(default=0, verbose_name='Puntos Históricos Acumulados')),
                ('redeemed_points', models.IntegerField(default=0, verbose_name='Puntos Canjeados Históricos')),
                ('referrals_count', models.PositiveIntegerField(default=0, verbose_name='Amigos Referidos')),
                ('anniversary_date', models.DateField(blank=True, null=True, verbose_name='Aniversario (Fecha Registro Club)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Referido por')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards.loyaltytier', verbose_name='Nivel Actual')),
            ],
            options={
                'verbose_name': 'Perfil Fidelización',
                'verbose_name_plural': 'Perfiles Fidelización',
                'ordering': ['-current_points'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Ganados'), ('REDEEM', 'Canjeados'), ('EXPIRE', 'Expirados'), ('ADJUST', 'Ajuste Manual')], db_index=True, max_length=10, verbose_name='Tipo Movimiento')),
                ('amount', models.IntegerField(verbose_name='Puntos (positivo=ganados, negativo=canjeados)')),
                ('balance_after', models.IntegerField(editable=False, verbose_name='Saldo después')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Expiración (solo ganados)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_tx', to='refreshments.order', verbose_name='Pedido asociado')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_performed', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_tx', to='reservations.reservation', verbose_name='Reserva asociada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_tx', to='rewards.rewardcatalogitem', verbose_name='Premio canjeado')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards.rewardrule', verbose_name='Regla Aplicada')),
            ],
            options={
                'verbose_name': 'Transacción Puntos',
                'verbose_name_plural': 'Transacciones Puntos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'transaction_type', 'created_at'], name='rewards_poi_user_id_16bbc6_idx')],
            },
        ),
    ]
