# Generated by Django 5.0.14 on 2026-08-18 02:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'Este email ya se encuentra registrado'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Email inválido')], verbose_name='Correo Electrónico')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Solo letras, números, ., _ , + y - permitidos', regex='^[a-zA-Z0-9_.+-]+$')], verbose_name='Nombre de usuario')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLOYEE', 'Empleado / Recepción'), ('CLIENT', 'Cliente')], db_index=True, default='CLIENT', max_length=20, verbose_name='Rol del sistema')),
                ('is_active', models.BooleanField(default=True, help_text='Inactivo = no puede iniciar sesión (Ley 1581 - desautorización)', verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Puede acceder al panel administrativo Django', verbose_name='Staff')),
                ('is_verified', models.BooleanField(default=False, help_text='El usuario validó su correo', verbose_name='Email Verificado')),
                ('accepted_privacy_policy', models.BooleanField(default=False, help_text='Requerido por Ley 1581/2012 Protección de Datos', verbose_name='Aceptó Política Privacidad (Ley 1581)')),
                ('accepted_terms', models.BooleanField(default=False, verbose_name='Aceptó Términos y Condiciones')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('NIT', 'NIT')], default='CC', max_length=5, verbose_name='Tipo Documento')),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Número Documento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=2, verbose_name='Género')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CO', verbose_name='Teléfono / Celular')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Dirección Residencia')),
                ('city', models.CharField(default='Maicao', max_length=80, verbose_name='Ciudad')),
                ('department', models.CharField(default='La Guajira', max_length=80, verbose_name='Departamento')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto Emergencia (Nombre)')),
                ('emergency_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CO', verbose_name='Teléfono Emergencia')),
                ('membership_type', models.CharField(blank=True, help_text='Ej: Básico, Premium, Oro', max_length=50, null=True, verbose_name='Tipo Membresía')),
                ('membership_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento Membresía')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP Último Login')),
                ('last_login_user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent Último Login')),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aceptación Privacidad')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
                'permissions': (('can_view_dashboard_admin', 'Puede ver panel admin'), ('can_manage_users', 'Puede gestionar usuarios'), ('can_manage_all_reservations', 'Puede gestionar todas las reservas'), ('can_manage_refreshments', 'Puede gestionar refresquería'), ('can_manage_rewards', 'Puede gestionar recompensas'), ('can_manage_gym', 'Puede gestionar gimnasio'), ('can_view_reports', 'Puede ver reportes')),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGIN_FAIL', 'Login Fallido'), ('LOGOUT', 'Cierre de Sesión'), ('PROFILE_VIEW', 'Visualización Perfil'), ('PROFILE_EDIT', 'Edición Perfil'), ('DATA_EXPORT', 'Exportación Datos'), ('DATA_DELETE', 'Eliminación Datos')], db_index=True, max_length=30, verbose_name='Acción')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha/Hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro Auditoría',
                'verbose_name_plural': 'Registros Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='authenticat_role_bc9683_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'first_name'], name='authenticat_last_na_f883b4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action', 'created_at'], name='authenticat_user_id_602673_idx'),
        ),
    ]
