# Generated by Django 5.0.14 on 2026-08-18 02:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Equipo')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Equipo Gimnasio',
                'verbose_name_plural': 'Equipos Gimnasio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre Grupo Muscular')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='💪', max_length=10, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Grupo Muscular',
                'verbose_name_plural': 'Grupos Musculares',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre Ejercicio')),
                ('slug', models.SlugField(unique=True)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Principiante'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado')], default='BEGINNER', max_length=20, verbose_name='Nivel Dificultad')),
                ('description', models.TextField(help_text='Pasos detallados para realizar el ejercicio', max_length=1000, verbose_name='Instrucciones')),
                ('tips', models.TextField(blank=True, max_length=500, null=True, verbose_name='Consejos / Postura')),
                ('common_mistakes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Errores Comunes')),
                ('recommended_sets', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Series recomendadas')),
                ('recommended_reps_min', models.PositiveIntegerField(default=8, verbose_name='Repeticiones mínimas')),
                ('recommended_reps_max', models.PositiveIntegerField(default=12, verbose_name='Repeticiones máximas')),
                ('rest_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)], verbose_name='Descanso (segundos)')),
                ('estimated_calories_per_set', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías aprox por serie')),
                ('video_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='URL Video tutorial')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gym/exercises/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible a clientes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'EMPLOYEE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='gym.equipment', verbose_name='Equipo Principal')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='gym.musclegroup', verbose_name='Grupo Muscular Principal')),
                ('secondary_groups', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='gym.musclegroup', verbose_name='Grupos Musculares Secundarios')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['muscle_group__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='gym.musclegroup', verbose_name='Grupos Musculares que trabaja'),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Rutina')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('goal', models.CharField(choices=[('STRENGTH', 'Fuerza'), ('HYPERTROPHY', 'Hipertrofia (Volumen)'), ('DEFINITION', 'Definición'), ('WEIGHT_LOSS', 'Pérdida de Peso'), ('GENERAL', 'Acondicionamiento General')], db_index=True, default='GENERAL', max_length=30, verbose_name='Objetivo Principal')),
                ('duration', models.CharField(choices=[('SHORT', 'Corta (< 30 min)'), ('MEDIUM', 'Media (30-60 min)'), ('LONG', 'Larga (> 60 min)')], default='MEDIUM', max_length=20, verbose_name='Duración Estimada')),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Principiante'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado')], default='BEGINNER', max_length=20, verbose_name='Nivel Recomendado')),
                ('frequency_days', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Días por semana sugeridos')),
                ('estimated_weeks', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Duración sugerida en semanas')),
                ('is_generic', models.BooleanField(db_index=True, default=True, verbose_name='Rutina Genérica (todos los clientes)')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válida desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válida hasta')),
                ('warm_up', models.TextField(blank=True, default='5-10 min caminata elíptica o trote suave + movilidad articular', max_length=500, null=True, verbose_name='Calentamiento')),
                ('cool_down', models.TextField(blank=True, default='5-10 min estiramiento global + respiración profunda', max_length=500, null=True, verbose_name='Enfriamiento / Estiramiento')),
                ('nutrition_tips', models.TextField(blank=True, max_length=700, null=True, verbose_name='Recomendaciones Nutricionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gym/routines/%Y/%m/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'EMPLOYEE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Asignada por')),
                ('assigned_client', models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_routines', to=settings.AUTH_USER_MODEL, verbose_name='Cliente específico (si no es genérica)')),
                ('muscle_groups', models.ManyToManyField(blank=True, related_name='routines', to='gym.musclegroup', verbose_name='Grupos Musculares involucrados')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden en la rutina')),
                ('sets', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Series')),
                ('reps', models.CharField(default='10-12', max_length=30, verbose_name='Repeticiones (ej: 10-12)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso sugerido (kg)')),
                ('rest_seconds', models.PositiveIntegerField(default=60, verbose_name='Descanso (segundos)')),
                ('notes', models.TextField(blank=True, max_length=300, null=True, verbose_name='Notas específicas cliente')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_instances', to='gym.exercise', verbose_name='Ejercicio')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='gym.routine', verbose_name='Rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio en Rutina',
                'verbose_name_plural': 'Ejercicios en Rutinas',
                'ordering': ['routine', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha Sesión')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Duración (min)')),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías quemadas (aprox)')),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('feeling', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Sensación 1-10')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='gym.routine')),
            ],
            options={
                'verbose_name': 'Registro Entrenamiento',
                'verbose_name_plural': 'Registros Entrenamientos',
                'ordering': ['-session_date'],
            },
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['is_generic', 'is_active', 'goal'], name='gym_routine_is_gene_b4e6ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routineexercise',
            unique_together={('routine', 'exercise', 'order')},
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['client', 'session_date'], name='gym_workout_client__b90c4f_idx'),
        ),
    ]
