# Generated by Django 5.0.14 on 2026-08-18 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INFO', 'Informativa'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('DANGER', 'Urgente'), ('RESERVATION', 'Actualización Reserva'), ('ORDER', 'Actualización Pedido'), ('REWARD', 'Recompensa')], db_index=True, default='INFO', max_length=20)),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('message', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('related_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta Relacionada')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destino')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='reports_not_user_id_b408b1_idx')],
            },
        ),
    ]
